name: vtach-env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - scikit-learn=1.4.2
  - scipy=1.12.0
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pip=24.0
  - pip:
      - kagglehub==0.2.5
      - neurokit2==0.2.7
